import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#191a1a",
        "tertiary": "#7af4ff",
        "on-secondary": "#005f2a",
        "error-dim": "#d53d18",
        "tertiary-container": "#07ebf8",
        "surface-variant": "#262626",
        "on-tertiary-container": "#005257",
        "tertiary-dim": "#00dbe8",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#565555",
        "secondary-fixed": "#8ff9a4",
        "primary-fixed-dim": "#0d47a1",
        "primary-dim": "#0d47a1",
        "background": "#0e0e0e",
        "primary-container": "#1565c0",
        "on-secondary-container": "#e4ffe3",
        "surface-container-low": "#131313",
        "on-primary-fixed-variant": "#1565c0",
        "on-primary-fixed": "#002171",
        "on-tertiary-fixed": "#003d41",
        "secondary": "#8ff9a4",
        "outline-variant": "#484848",
        "on-primary-container": "#e3f2fd",
        "surface-tint": "#0f52ba",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "error": "#ff7351",
        "surface": "#0e0e0e",
        "surface-container-highest": "#262626",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#0f52ba",
        "surface-bright": "#2c2c2c",
        "on-error": "#450900",
        "error-container": "#b92902",
        "on-surface-variant": "#adaaaa",
        "outline": "#767575",
        "on-tertiary-fixed-variant": "#005c62",
        "on-tertiary": "#005b61",
        "secondary-fixed-dim": "#81ea97",
        "on-surface": "#ffffff",
        "tertiary-fixed": "#07ebf8",
        "inverse-primary": "#0d47a1",
        "surface-container-high": "#202020",
        "on-secondary-fixed": "#004a1f",
        "primary": "#0f52ba",
        "on-error-container": "#ffd2c8",
        "tertiary-fixed-dim": "#00dbe8",
        "secondary-dim": "#81ea97",
        "secondary-container": "#006d32",
        "on-secondary-fixed-variant": "#006a30",
        },
        fontFamily: {
            "headline": ["var(--font-manrope)", "sans-serif"],
            "body": ["var(--font-inter)", "sans-serif"],
            "label": ["var(--font-inter)", "sans-serif"]
        },
        borderRadius: {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
    },
  },
  plugins: [],
};
export default config;
